### ISSUE TITLE
github.io + Chrome and insecure content

### ISSUE THREAD

**Issue by spgolden** [cs109/2014#4]
A small cosmetic issue, but Chrome and Firefox don't want to load the style sheets for the github.io page.

![image](https://cloud.githubusercontent.com/assets/3937928/5316811/a2388f86-7c98-11e4-973b-cd55c575337d.png)

Doesn't load in Chrome 39.0.2171.71
Doesn't load in Firefox 33.1

Works in Safari 7.1

I suspect if you update _config.yml to https it should work.

**Comment by stephaniehicks** [comment]
Hi, I just checked the website in Chrome Version 39.0.2171.95 and the style sheet loaded. I don't have Firefox, but I can test that out tomorrow.
